CREATE TABLE "ATG_4085_Router_Chng"(
 "RCID" IDENTITY DEFAULT '0',
 "Router" CHAR(20),
 "ProductLine" CHAR(2),
 "WC" CHAR(4),
 "Part" CHAR(20),
 "Seq" CHAR(6),
 "OldRuntime" NUMERIC(12,4),
 "NewRuntime" NUMERIC(12,4),
 "OldSetup" NUMERIC(12,4),
 "NewSetup" NUMERIC(12,4),
 "OldQty" NUMERIC(12,4),
 "NewQty" NUMERIC(12,4),
 "UpdateDT" DATETIME,
 "GSUser" CHAR(8),
 "ChangeType" INTEGER,
 "JobSfx" CHAR(9),
 "RequestDate" DATE,
 "RequestingUser" CHAR(8),
 "Comments" LONGVARCHAR,
 "OldRate" NUMERIC(12,4),
 "NewRate" NUMERIC(12,4),
 "OldVendor" CHAR(6),
 "NewVendor" CHAR(6),
 "OldPart" CHAR(20),
 PRIMARY KEY ("RCID"),
 UNIQUE ("RCID"));